"""Add Food model

Revision ID: 943be873fe2c
Revises: 8bb4c5f4ae58
Create Date: 2025-01-23 06:14:09.209704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943be873fe2c'
down_revision = '8bb4c5f4ae58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bartender_transactions', schema=None) as batch_op:
        batch_op.alter_column('bartender_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bartender_transactions', schema=None) as batch_op:
        batch_op.alter_column('bartender_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
