"""Add status and difference to SalesTransaction

Revision ID: 9ab16771af61
Revises: 
Create Date: 2025-07-28 07:50:42.469403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab16771af61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('difference', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_transaction', schema=None) as batch_op:
        batch_op.drop_column('difference')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
